version: "3.9"
services:
  server:
    build: .
    ports:
      - "11000:3000"
    volumes:
        - type: bind
          source: /dados01/workspace/ufmg_2021_d02/great_expectations_zeppelin/uncommitted/data_docs/local_site
          target: /static
